%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 848
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 427.123046875
   fy: 427.123046875
   cx: 426.35699462890625
   cy: 239.0784454345703
